### ISSUE TITLE
Cannot override "iam_access_key_max_age" easily?

### ISSUE THREAD

**Issue by dejwsz** [cloudposse/terraform-aws-iam-s3-user#43]
"iam_access_key_max_age" cannot be changed? for example to 0?

**Comment by noqqe** [comment]
I'd love to see that as well!

**Comment by Nuru** [comment]
We are removing this feature due to the confusion to the community of our terraform users that has been caused by requiring the `cloudposse/awsutils` Terraform provider to provide the feature. The error messages stemming from the missing provider block configuration are causing more of a support headache than it is worth. Since we implemented this feature, most CI/CD providers have implemented a better way to obtain short-lived CI/CD credentials (e.g. GitHub Actions and CircleCI both support OIDC with AWS, GCP, Azure, etc).
